### ISSUE TITLE
PrismJSが原因で、denops上で動作しない問題

### ISSUE THREAD

**Issue by shuntaka9576** [hozi-dev/hozi-dev-packages#4]
ec67c68では動作することを確認

現時点で最新の22e7ae3では動作しないことを確認

```
[denops] (hozidev) TypeError: Cannot set properties of undefined (setting 'Prism')
[denops]     at Object.<anonymous> (file:///Users/shuntaka/Library/Caches/deno/npm/registry.npmjs.org/@hozi-dev/markdown-to-html/0.11.10/build/index.js:34:14)
[denops]     at Object.<anonymous> (file:///Users/shuntaka/Library/Caches/deno/npm/registry.npmjs.org/@hozi-dev/markdown-to-html/0.11.10/build/index.js:117:4)
[denops]     at Module._compile (node:module:731:36)
[denops]     at Object.Module._extensions..js (node:module:745:12)
[denops]     at Module.load (node:module:656:34)
[denops]     at Function.Module._load (node:module:539:16)
[denops]     at Module.require (node:module:675:23)
[denops]     at require (node:module:789:20)
[denops]     at file:///Users/shuntaka/Library/Caches/deno/npm/registry.npmjs.org/@hozi-dev/markdown-to-html/0.11.10/build/index.js:3:13
```

昔動作しなかったことはあった
https://zenn.dev/shuntaka/scraps/c59c6aae5db4fe

**Comment by shuntaka9576** [comment]
これでWebWorkerで動くように
https://github.com/shuntaka-dev/hozi-dev-packages/commit/a7df53661d8dfe0349db5fadc26882cf8414a380
